

esprit_user:
    resource: "@EspritUserBundle/Resources/config/routing.yml"
    prefix:   /

esprit_galerie:
    resource: "@EspritGalerieBundle/Resources/config/routing.yml"
    prefix:   /

fos_user: 
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"