security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                always_use_default_target_path: true
                default_target_path: /
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                invalidate_session: true
                path: /logout
                target: /login
            anonymous:    true
            
            